version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - jung_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - jung_static:/data/static/
      - jung_media:/data/media/

  django_container_gunicorn:
    image: django_test_image:5
    networks:
      - jung_network
    volumes:
      - jung_static:/home/meanwo/staticfiles/
      - jung_media:/home/meanwo/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - jung_network
    volumes:
      - jung_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  jung_network:

volumes:
  jung_static:
  jung_media:
  jung_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_USER:
    external: true