version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - jung_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - jung_static:/data/static/
      - jung_media:/data/media/
      - jung_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
    - 7890:7890
    volumes:
    - jung_log:/var/log/nginx/
    command: /var/log/nginx/jung_access.log -o /var/log/nginx/report.html --real-time-html --log-format COMBINED
  django_container_gunicorn:
    image: django_test_image:5
    networks:
      - jung_network
    volumes:
      - jung_static:/home/meanwo/staticfiles/
      - jung_media:/home/meanwo/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - jung_network
    volumes:
      - jung_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  jung_network:

volumes:
  jung_static:
  jung_media:
  jung_mariadb:
  jung_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  NGINX_AUTH:
    external: true